version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: decp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: LMS_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - decp-network

  backend:
    build:
      context: ./backend/decp-platform/decp-platform
      dockerfile: Dockerfile
    container_name: decp-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/LMS_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
    networks:
      - decp-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: decp-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - decp-network

volumes:
  db_data:

networks:
  decp-network:
    driver: bridge
